controller_list:
  - name: fake_x_arm_controller
    joints:
      - joint_axis_link1_to_base
      - joint_axis_link2_to_link1
      - joint_axis_link3_to_link2
      - joint_axis_link4_to_link3
      - joint_axis_link5_to_link4
      - joint_axis_link6_to_link5
      - joint_axis_link7_to_link6
  - name: fake_x_arm_calib_controller
    joints:
      - joint_axis_link1_to_base
      - joint_axis_link2_to_link1
      - joint_axis_link3_to_link2
      - joint_axis_link4_to_link3
      - joint_axis_link5_to_link4
      - joint_axis_calib_link6_to_link5
      - joint_axis_calib_link7_to_calib_link6
  - name: fake_x_hand_controller
    joints:
      - joint_axis_index0_to_handRoot
      - joint_axis_index1_to_index0
      - joint_axis_index2_to_index1
      - joint_axis_joint0_to_handRoot
      - joint_axis_little1_to_little0
      - joint_axis_little2_to_little1
      - joint_axis_middle0_to_handRoot
      - joint_axis_middle1_to_middle0
      - joint_axis_middle2_to_middle1
      - joint_axis_wedding0_to_handRoot
      - joint_axis_wedding1_to_wedding0
      - joint_axis_wedding2_to_wedding1