// Generated by gencpp from file reverse_kinematics/solutions.msg
// DO NOT EDIT!


#ifndef REVERSE_KINEMATICS_MESSAGE_SOLUTIONS_H
#define REVERSE_KINEMATICS_MESSAGE_SOLUTIONS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <reverse_kinematics/solution.h>

namespace reverse_kinematics
{
template <class ContainerAllocator>
struct solutions_
{
  typedef solutions_<ContainerAllocator> Type;

  solutions_()
    : solutions()  {
    }
  solutions_(const ContainerAllocator& _alloc)
    : solutions(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::reverse_kinematics::solution_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::reverse_kinematics::solution_<ContainerAllocator> >::other >  _solutions_type;
  _solutions_type solutions;





  typedef boost::shared_ptr< ::reverse_kinematics::solutions_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::reverse_kinematics::solutions_<ContainerAllocator> const> ConstPtr;

}; // struct solutions_

typedef ::reverse_kinematics::solutions_<std::allocator<void> > solutions;

typedef boost::shared_ptr< ::reverse_kinematics::solutions > solutionsPtr;
typedef boost::shared_ptr< ::reverse_kinematics::solutions const> solutionsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::reverse_kinematics::solutions_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::reverse_kinematics::solutions_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace reverse_kinematics

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'reverse_kinematics': ['/home/x-arm/macaca/src/reverse_kinematics/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::reverse_kinematics::solutions_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::reverse_kinematics::solutions_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::reverse_kinematics::solutions_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::reverse_kinematics::solutions_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::reverse_kinematics::solutions_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::reverse_kinematics::solutions_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::reverse_kinematics::solutions_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f40e91418d35072b9f525091e7304f99";
  }

  static const char* value(const ::reverse_kinematics::solutions_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf40e91418d35072bULL;
  static const uint64_t static_value2 = 0x9f525091e7304f99ULL;
};

template<class ContainerAllocator>
struct DataType< ::reverse_kinematics::solutions_<ContainerAllocator> >
{
  static const char* value()
  {
    return "reverse_kinematics/solutions";
  }

  static const char* value(const ::reverse_kinematics::solutions_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::reverse_kinematics::solutions_<ContainerAllocator> >
{
  static const char* value()
  {
    return "solution[] solutions\n\
\n\
================================================================================\n\
MSG: reverse_kinematics/solution\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::reverse_kinematics::solutions_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::reverse_kinematics::solutions_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.solutions);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct solutions_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::reverse_kinematics::solutions_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::reverse_kinematics::solutions_<ContainerAllocator>& v)
  {
    s << indent << "solutions[]" << std::endl;
    for (size_t i = 0; i < v.solutions.size(); ++i)
    {
      s << indent << "  solutions[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::reverse_kinematics::solution_<ContainerAllocator> >::stream(s, indent + "    ", v.solutions[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // REVERSE_KINEMATICS_MESSAGE_SOLUTIONS_H
